server:
  port: 10000

spring:
  profiles:
    active: dev
  application:
    #\u8868\u793A\u6CE8\u518C\u5230eureka\u7684\u670D\u52A1\u540D
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    #\u8868\u793A\u662F\u5426\u5C06\u81EA\u5DF1\u6CE8\u518C\u5230 hyr-eureka-server \u9ED8\u8BA4\u4E3Atrue
    register-with-eureka: false
    #\u8868\u793A\u662F\u5426\u4ECE hyr-eureka-server \u83B7\u53D6\u6CE8\u518C\u4FE1\u606F\uFF0C \u9ED8\u8BA4\u4E3Atrue
    fetch-registry: false
    service-url:
      #\u8868\u793A\u6CE8\u518C\u5230 hyr-eureka-server \u7684\u5730\u5740
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

